name: Deploy CampusView

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: SSH into Server and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: 82.112.226.47
        username: root
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          cd ~/CampusView
          git pull origin main
          npm install
          pm2 restart campusview || pm2 start npm --name "campusview" -- start
          
